name: yoda
description: Effects widget, cut widgets in NxM tiles and animate them.
version: 0.0.1-dev.1
homepage: https://github.com/alnitak/yoda
issue_tracker: https://github.com/alnitak/yoda/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
